# Config version 0.2

system:
  debug:
    enable: false
    level: low
  runtime:
    # RELEASE - синхронизировать локализации с GitHub при запуске
    # dev     - использовать локальные файлы, GitHub не трогать
    profile: RELEASE

database:
  type: mysql/sqlite
  mysql:
    login: "user"
    password: "password"
    url-connect: "jdbc:mysql://127.0.0.1:3306/BotDatabase?autoReconnect=true"
  postgres:
    login: "user"
    password: "password"
    url-connect: "jdbc:postgres://127.0.0.1:3306/BotDatabase?autoReconnect=true"

bot:
  token: "token"
  activity:
    type: playing
    text: We create our own lives, and the forge of emptiness is the beginning from which we start building our lives!
    streaming-url: https://www.twitch.tv/sahesha

channel:
  news: fill_id_news
  checklist: fill_id_checklist
  feedback:
    message: ""
    ideas: ""
    moderation: ""
    user: ""

levels:
  base-xp: 100
  growth: 1.2
  xp-per-message: 5
  xp-per-voice-minute: 5
  message-cooldown-seconds: 60
  channel: ""

lavalink:
  node:
    1:
      name: "Cool node #1"
      url: "ws://127.0.0.1:2333"
      password: "VeryGoodPassword1234_Qwerty"

web-api:
  port: 1111

other:
  kawaii-api:
    enable: true
    token: ""
  youtube-api:
    token: "token"
  minecraft:
    enable: true
    websocket-api: "ws://127.0.0.1:8765"
    channel: 1392542412735385843
